### ISSUE TITLE
Shareable URL

### ISSUE THREAD

**Issue by sluongng** [registrybuild/registry.build#1]
![image](https://github.com/registrybuild/registry.build/assets/26684313/9913fa3f-433c-49a2-884e-c15767f700a0)

It would be nice if we could predefine a set of configs like this and get a shareable URL to share with others.

**Comment by siggisim** [comment]
Configs are now shareable (selection state is now stored in the URL).

I would not yet consider these URL parameters stable / final though, and they'll likely change as we refine the configuration options / format.
